//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.21 at 03:00:35 PM EET 
//


package oasis.names.specification.ubl.schema.xsd.api;

import oasis.names.specification.ubl.schema.xsd.waybill_2.Waybill;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.specification.ubl.schema.xsd.waybill_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UBLMessageWrapper_QNAME = new QName("com.propentus.smartlog.api", "Messages");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.specification.ubl.schema.xsd.waybill_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Waybill }
     * 
     */
    public UBLMessageWrapper createMessagesType() {
        return new UBLMessageWrapper();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Waybill }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "com.propentus.smartlog.api", name = "UBLMessageWrapper")
    public JAXBElement<UBLMessageWrapper> createUBLMessageWrapper(UBLMessageWrapper value) {
        return new JAXBElement<UBLMessageWrapper>(_UBLMessageWrapper_QNAME, UBLMessageWrapper.class, null, value);
    }

}
