//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 03:30:58 PM EET 
//


package oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2;

import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.BaseAmountType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT000001&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Amount. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A number of monetary units specified using a given unit of currency.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Amount&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for AmountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AmountType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>AmountType">
 *       &lt;attribute name="currencyID" use="required" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AmountType")
@XmlSeeAlso({
    BaseAmountType.class,
    /*DeclaredStatisticsValueAmountType.class,
    PayableAlternativeAmountType.class,
    PayableAmountType.class,
    MaximumAdvertisementAmountType.class,
    TaxEnergyAmountType.class,
    EstimatedOverallContractAmountType.class,
    InventoryValueAmountType.class,
    DocumentationFeeAmountType.class,
    PayableRoundingAmountType.class,
    MaximumAmountType.class,
    oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.AmountType.class,
    HigherTenderAmountType.class,
    DeclaredCarriageValueAmountType.class,
    ChargeTotalAmountType.class,
    FeeAmountType.class,
    TotalPaymentAmountType.class,
    TaxEnergyOnAccountAmountType.class,
    TaxExclusiveAmountType.class,
    TaxInclusiveAmountType.class,
    LineExtensionAmountType.class,
    DebitLineAmountType.class,
    PartyCapacityAmountType.class,
    ValueAmountType.class,
    CorrectionAmountType.class,
    PriceAmountType.class,
    RoundingAmountType.class,
    PenaltyAmountType.class,
    LowerTenderAmountType.class,
    CorrectionUnitAmountType.class,
    BalanceAmountType.class,
    AllowanceTotalAmountType.class,
    TaxAmountType.class,
    AverageSubsequentContractAmountType.class,
    LiabilityAmountType.class,
    TransactionCurrencyTaxAmountType.class,
    TotalTaxAmountType.class,
    CallBaseAmountType.class,
    MaximumPaidAmountType.class,
    TotalAmountType.class,
    CorporateStockAmountType.class,
    RequiredFeeAmountType.class,
    AdvertisementAmountType.class,
    PaidAmountType.class,
    TotalInvoiceAmountType.class,
    ThresholdAmountType.class,
    TaxableAmountType.class,
    InsurancePremiumAmountType.class,
    FreeOnBoardValueAmountType.class,
    PerUnitAmountType.class,
    CallExtensionAmountType.class,
    CreditLineAmountType.class,
    PrepaidAmountType.class,
    AnnualAverageAmountType.class,
    DeclaredForCarriageValueAmountType.class,
    MinimumAmountType.class,
    FaceValueAmountType.class,
    SettlementDiscountAmountType.class,
    TotalTaskAmountType.class,
    TotalCreditAmountType.class,
    EstimatedAmountType.class,
    TotalBalanceAmountType.class,
    TaxEnergyBalanceAmountType.class,
    InsuranceValueAmountType.class,
    AverageAmountType.class,
    TotalDebitAmountType.class,
    MarketValueAmountType.class,
    DeclaredCustomsValueAmountType.class*/
})
public class AmountType
    extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.AmountType
{


}
