//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 03:30:58 PM EET 
//


package oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2;

import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.*;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionAgencyIDType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionAgencyURIType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionURIType;
import oasis.names.specification.ubl.schema.xsd.commonextensioncomponents_2.ExtensionVersionIDType;
import oasis.names.specification.ubl.schema.xsd.signaturebasiccomponents_2.ReferencedSignatureIDType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000011&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Identifier. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string to identify and uniquely distinguish one instance of an object in an identification scheme from all other objects in the same scheme, together with relevant supplementary information.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Identifier&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Other supplementary components in the CCT are captured as part of the token and name for the schema module containing the identifier list and thus, are not declared as attributes. &lt;/ccts:UsageRule&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for IdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifierType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>IdentifierType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifierType")
@XmlSeeAlso({
    PerformingCarrierAssignedIDType.class,
    BuyerProfileURIType.class,
    CustomerAssignedAccountIDType.class,
    IssuerIDType.class,
    LoadingSequenceIDType.class,
    HazardClassIDType.class,
    SuccessiveSequenceIDType.class,
    CV2IDType.class,
    AircraftIDType.class,
    EndpointIDType.class,
    SecurityIDType.class,
    TransportExecutionPlanReferenceIDType.class,
    CompanyIDType.class,
    UBLVersionIDType.class,
    LocationIDType.class,
    IDType.class,
    OntologyURIType.class,
    URIType.class,
    BuyerEventIDType.class,
    RevisedForecastLineIDType.class,
    AccountIDType.class,
    ExchangeMarketIDType.class,
    ParentDocumentVersionIDType.class,
    PrimaryAccountNumberIDType.class,
    LogoReferenceIDType.class,
    RequestForQuotationLineIDType.class,
    ConsumptionReportIDType.class,
    ConsumptionIDType.class,
    RadioCallSignIDType.class,
    RegistrationIDType.class,
    SignatureIDType.class,
    TransportationServiceDetailsURIType.class,
    ExtendedIDType.class,
    LowerOrangeHazardPlacardIDType.class,
    PrepaidPaymentReferenceIDType.class,
    NationalityIDType.class,
    AwardingCriterionIDType.class,
    TrainIDType.class,
    SubscriberIDType.class,
    PaymentMeansIDType.class,
    CustomizationIDType.class,
    IssueNumberIDType.class,
    OpenTenderIDType.class,
    SchemeURIType.class,
    SerialIDType.class,
    AuctionURIType.class,
    RailCarIDType.class,
    BusinessClassificationEvidenceIDType.class,
    UUIDType.class,
    BarcodeSymbologyIDType.class,
    CarrierAssignedIDType.class,
    PaymentIDType.class,
    ReferenceIDType.class,
    ContractedCarrierAssignedIDType.class,
    BusinessIdentityEvidenceIDType.class,
    OriginalContractingSystemIDType.class,
    PreviousVersionIDType.class,
    VersionIDType.class,
    AttributeIDType.class,
    ParentDocumentLineReferenceIDType.class,
    InformationURIType.class,
    JourneyIDType.class,
    ConsigneeAssignedIDType.class,
    InstructionIDType.class,
    ValidatorIDType.class,
    ProfileExecutionIDType.class,
    EconomicOperatorRegistryURIType.class,
    FreightForwarderAssignedIDType.class,
    DocumentIDType.class,
    TenderEnvelopeIDType.class,
    SequenceIDType.class,
    NetworkIDType.class,
    SpecificationIDType.class,
    ContractFolderIDType.class,
    SequenceNumberIDType.class,
    ProductTraceIDType.class,
    SupplierAssignedAccountIDType.class,
    LicensePlateIDType.class,
    RegistrationNationalityIDType.class,
    ChipApplicationIDType.class,
    TrackingIDType.class,
    MarkingIDType.class,
    UpperOrangeHazardPlacardIDType.class,
    PreviousJobIDType.class,
    LotNumberIDType.class,
    BrokerAssignedIDType.class,
    TraceIDType.class,
    AdditionalAccountIDType.class,
    VesselIDType.class,
    VariantIDType.class,
    RequiredCustomsIDType.class,
    LanguageIDType.class,
    SalesOrderIDType.class,
    ConsignorAssignedIDType.class,
    SalesOrderLineIDType.class,
    ShippingOrderIDType.class,
    PaymentTermsDetailsURIType.class,
    ImmobilizationCertificateIDType.class,
    AgencyIDType.class,
    ParentDocumentIDType.class,
    LineIDType.class,
    ReleaseIDType.class,
    OriginalJobIDType.class,
    WebsiteURIType.class,
    ReferencedConsignmentIDType.class,
    IdentificationIDType.class,
    ProfileIDType.class,
    SellerEventIDType.class,
    ExtensionAgencyURIType.class,
    ExtensionVersionIDType.class,
    ExtensionURIType.class,
    ExtensionAgencyIDType.class,
    ReferencedSignatureIDType.class
})
public class IdentifierType
    extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.IdentifierType
{


}
