//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 03:30:58 PM EET 
//


package oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2;

import javax.xml.bind.annotation.*;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000012&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Indicator. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A list of two mutually exclusive Boolean values that express the only possible states of a property.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Indicator&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for IndicatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndicatorType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndicatorType", propOrder = {
    "value"
})
@XmlSeeAlso({
    /*MarkAttentionIndicatorType.class,
    AnimalFoodApprovedIndicatorType.class,
    LegalStatusIndicatorType.class,
    RefrigerationOnIndicatorType.class,
    RequiredCurriculaIndicatorType.class,
    VariantConstraintIndicatorType.class,
    IndicationIndicatorType.class,
    ToOrderIndicatorType.class,
    PartialDeliveryIndicatorType.class,
    PowerIndicatorType.class,
    BalanceBroughtForwardIndicatorType.class,
    BindingOnBuyerIndicatorType.class,
    AuctionConstraintIndicatorType.class,
    CandidateReductionConstraintIndicatorType.class,
    StatusAvailableIndicatorType.class,
    HumanFoodApprovedIndicatorType.class,
    SoleProprietorshipIndicatorType.class,
    PricingUpdateRequestIndicatorType.class,
    BackOrderAllowedIndicatorType.class,
    ThirdPartyPayerIndicatorType.class,
    FullyPaidSharesIndicatorType.class,
    CompletionIndicatorType.class,
    AcceptedIndicatorType.class,
    AnimalFoodIndicatorType.class,
    FreeOfChargeIndicatorType.class,
    SpecialSecurityIndicatorType.class,
    FollowupContractIndicatorType.class,
    TaxEvidenceIndicatorType.class,
    DangerousGoodsApprovedIndicatorType.class,
    OptionalLineItemIndicatorType.class,
    ReturnabilityIndicatorType.class,
    OrderableIndicatorType.class,
    CopyIndicatorType.class,
    SplitConsignmentIndicatorType.class,
    HazardousRiskIndicatorType.class,
    PrizeIndicatorType.class,
    UnknownPriceIndicatorType.class,
    TaxIncludedIndicatorType.class,
    ItemUpdateRequestIndicatorType.class,
    CustomsImportClassifiedIndicatorType.class,
    ChargeIndicatorType.class,
    MarkCareIndicatorType.class,
    BulkCargoIndicatorType.class,
    GeneralCargoIndicatorType.class,
    PublishAwardIndicatorType.class,
    FrozenDocumentIndicatorType.class,
    LivestockIndicatorType.class,
    GovernmentAgreementConstraintIndicatorType.class,
    HumanFoodIndicatorType.class,
    ConsolidatableIndicatorType.class,
    OtherConditionsIndicatorType.class,
    RefrigeratedIndicatorType.class,
    ReturnableMaterialIndicatorType.class,
    PreCarriageIndicatorType.class,
    OnCarriageIndicatorType.class,
    ContainerizedIndicatorType.class,
    AdValoremIndicatorType.class,
    CatalogueIndicatorType.class,
    PrepaidIndicatorType.class,
    BasedOnConsensusIndicatorType.class*/
})
public class IndicatorType {

    @XmlValue
    protected boolean value;

    /**
     * Gets the value of the value property.
     * 
     */
    public boolean isValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(boolean value) {
        this.value = value;
    }

}
