//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 03:30:58 PM EET 
//


package oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2;

import oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.*;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000018&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Quantity. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A counted number of non-monetary units, possibly including a fractional part.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Quantity&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;decimal&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for QuantityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuantityType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>QuantityType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantityType")
@XmlSeeAlso({
    CrewQuantityType.class,
    TotalConsumedQuantityType.class,
    OperatingYearsQuantityType.class,
    TotalMeteredQuantityType.class,
    NormalTemperatureReductionQuantityType.class,
    EstimatedOverallContractQuantityType.class,
    ChargeableQuantityType.class,
    MinimumQuantityType.class,
    EmployeeQuantityType.class,
    ConsignmentQuantityType.class,
    EstimatedConsumedQuantityType.class,
    MinimumBackorderQuantityType.class,
    MaximumOrderQuantityType.class,
    MaximumBackorderQuantityType.class,
    ThresholdQuantityType.class,
    ExpectedQuantityType.class,
    TotalPackagesQuantityType.class,
    ReceivedTenderQuantityType.class,
    ExpectedOperatorQuantityType.class,
    MaximumQuantityType.class,
    MultipleOrderQuantityType.class,
    MaximumOperatorQuantityType.class,
    ConsumptionEnergyQuantityType.class,
    BaseQuantityType.class,
    TotalDeliveredQuantityType.class,
    PerformanceValueQuantityType.class,
    MinimumInventoryQuantityType.class,
    RejectedQuantityType.class,
    PassengerQuantityType.class,
    ShortQuantityType.class,
    ConsumptionWaterQuantityType.class,
    TimeDeltaDaysQuantityType.class,
    ContentUnitQuantityType.class,
    DifferenceTemperatureReductionQuantityType.class,
    ReturnableQuantityType.class,
    TotalGoodsItemQuantityType.class,
    PreviousMeterQuantityType.class,
    VarianceQuantityType.class,
    CreditedQuantityType.class,
    CustomsTariffQuantityType.class,
    ActualTemperatureReductionQuantityType.class,
    InvoicedQuantityType.class,
    ConsumerUnitQuantityType.class,
    ReceivedElectronicTenderQuantityType.class,
    GasPressureQuantityType.class,
    BasicConsumedQuantityType.class,
    OutstandingQuantityType.class,
    ValueQuantityType.class,
    LatestMeterQuantityType.class,
    ChildConsignmentQuantityType.class,
    SharesNumberQuantityType.class,
    TargetInventoryQuantityType.class,
    TotalPackageQuantityType.class,
    BatchQuantityType.class,
    MinimumOrderQuantityType.class,
    OversupplyQuantityType.class,
    MaximumVariantQuantityType.class,
    ReceivedQuantityType.class,
    DebitedQuantityType.class,
    DeliveredQuantityType.class,
    PackQuantityType.class,
    ReceivedForeignTenderQuantityType.class,
    BackorderQuantityType.class,
    oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.QuantityType.class,
    TotalTransportHandlingUnitQuantityType.class
})
public class QuantityType
    extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.QuantityType
{


}
