//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 03:30:58 PM EET 
//


package oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000019&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string (i.e. a finite set of characters), generally in the form of words of a language.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for TextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>TextType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType")
@XmlSeeAlso({
    /*PreviousMeterReadingMethodType.class,
    NegotiationDescriptionType.class,
    DocumentStatusReasonDescriptionType.class,
    HashAlgorithmMethodType.class,
    DemurrageInstructionsType.class,
    AwardingCriterionDescriptionType.class,
    XPathType.class,
    RankType.class,
    ConsumersEnergyLevelType.class,
    RemarksType.class,
    PersonalSituationType.class,
    PayerReferenceType.class,
    PriceTypeType.class,
    PrintQualifierType.class,
    AgencyNameType.class,
    ConditionType.class,
    LowTendersDescriptionType.class,
    StatusReasonType.class,
    ValidateProcessType.class,
    ValidateToolVersionType.class,
    FundingProgramType.class,
    CompanyLegalFormType.class,
    DeliveryInstructionsType.class,
    TelefaxType.class,
    MarkCareType.class,
    AllowanceChargeReasonType.class,
    WarrantyInformationType.class,
    LegalReferenceType.class,
    SubscriberTypeType.class,
    TariffDescriptionType.class,
    oasis.names.specification.ubl.schema.xsd.commonbasiccomponents_2.TextType.class,
    AdditionalConditionsType.class,
    MonetaryScopeType.class,
    InstructionNoteType.class,
    AcceptedVariantsDescriptionType.class,
    ConsumptionLevelType.class,
    ContractTypeType.class,
    PrizeDescriptionType.class,
    TaxExemptionReasonType.class,
    LossRiskType.class,
    ElectronicMailType.class,
    TransportServiceProviderRemarksType.class,
    SpecialTransportRequirementsType.class,
    ActivityTypeType.class,
    RoleDescriptionType.class,
    DocumentDescriptionType.class,
    OrganizationDepartmentType.class,
    MeterNameType.class,
    MarkAttentionType.class,
    CustomerReferenceType.class,
    JobTitleType.class,
    ExemptionReasonType.class,
    TimingComplaintType.class,
    CancellationNoteType.class,
    CalculationExpressionType.class,
    RejectReasonType.class,
    TestMethodType.class,
    CountrySubentityType.class,
    RegionType.class,
    DistrictType.class,
    SealingPartyTypeType.class,
    PasswordType.class,
    PriceChangeReasonType.class,
    DocumentTypeType.class,
    PurposeType.class,
    PostboxType.class,
    PlacardNotationType.class,
    TelecommunicationsSupplyTypeType.class,
    ApprovalStatusType.class,
    HeatingTypeType.class,
    LoginType.class,
    SpecialServiceInstructionsType.class,
    CustomsClearanceServiceInstructionsType.class,
    WorkPhaseType.class,
    TimeAmountType.class,
    TradingRestrictionsType.class,
    CharacteristicsType.class,
    JustificationDescriptionType.class,
    TierRangeType.class,
    PriorityType.class,
    ChannelType.class,
    OutstandingReasonType.class,
    ResolutionType.class,
    OneTimeChargeTypeType.class,
    OptionsDescriptionType.class,
    ConsumptionTypeType.class,
    TransportUserRemarksType.class,
    ValueQualifierType.class,
    MovieTitleType.class,
    JustificationType.class,
    TransportUserSpecialTermsType.class,
    LineType.class,
    ProcessDescriptionType.class,
    NoteType.class,
    PriceRevisionFormulaDescriptionType.class,
    WeightType.class,
    CertificateTypeType.class,
    HandlingInstructionsType.class,
    CodeValueType.class,
    RoomType.class,
    ShippingMarksType.class,
    ContractNameType.class,
    LatestMeterReadingMethodType.class,
    ConditionsDescriptionType.class,
    ExclusionReasonType.class,
    DocumentHashType.class,
    ServiceNumberCalledType.class,
    ContractSubdivisionType.class,
    DataSendingCapabilityType.class,
    CandidateStatementType.class,
    PaymentNoteType.class,
    ExpressionType.class,
    PostalZoneType.class,
    ConditionsType.class,
    CorrectionTypeType.class,
    MinimumImprovementBidType.class,
    SpecialTermsType.class,
    MeterConstantType.class,
    ValueType.class,
    BuyerReferenceType.class,
    TelephoneType.class,
    InformationType.class,
    ValidateToolType.class,
    CurrentChargeTypeType.class,
    CommentType.class,
    OrderableUnitType.class,
    TransportServiceProviderSpecialTermsType.class,
    BackorderReasonType.class,
    LimitationDescriptionType.class,
    RegulatoryDomainType.class,
    SummaryDescriptionType.class,
    PaymentDescriptionType.class,
    ElectronicDeviceDescriptionType.class,
    DepartmentType.class,
    BirthplaceNameType.class,
    RejectionNoteType.class,
    TelecommunicationsServiceCategoryType.class,
    CarrierServiceInstructionsType.class,
    TimezoneOffsetType.class,
    PlotIdentificationType.class,
    SpecialInstructionsType.class,
    PaymentOrderReferenceType.class,
    BuildingNumberType.class,
    FrequencyType.class,
    PhoneNumberType.class,
    ListValueType.class,
    ProcessReasonType.class,
    PayPerViewType.class,
    FeeDescriptionType.class,
    InvoicingPartyReferenceType.class,
    OtherInstructionType.class,
    DutyType.class,
    TitleType.class,
    ExtensionType.class,
    MeterNumberType.class,
    TechnicalCommitteeDescriptionType.class,
    MinimumValueType.class,
    LocationType.class,
    InhouseMailType.class,
    ServiceTypeType.class,
    ChangeConditionsType.class,
    InstructionsType.class,
    SignatureMethodType.class,
    DescriptionType.class,
    PackingMaterialType.class,
    ResidenceTypeType.class,
    MeterReadingCommentsType.class,
    AdditionalInformationType.class,
    KeywordType.class,
    ReferenceType.class,
    ForwarderServiceInstructionsType.class,
    MeterReadingTypeType.class,
    TelecommunicationsServiceCallType.class,
    HaulageInstructionsType.class,
    DamageRemarksType.class,
    NameSuffixType.class,
    PlacardEndorsementType.class,
    ShipsRequirementsType.class,
    ContentType.class,
    RegistrationNationalityType.class,
    MaximumValueType.class,
    ReplenishmentOwnerDescriptionType.class,
    PartyTypeType.class,
    FloorType.class,
    TransportationServiceDescriptionType.class,
    AccountingCostType.class,
    CanonicalizationMethodType.class,
    ExtensionAgencyNameType.class,
    ExtensionReasonType.class*/
})
public class TextType
    extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.TextType
{


}
