/*
 * DBE Core Complete API
 * Complete DBE Core API with all the defined API operations. Different API operations are also provided based on DBE Core roles as separate APIs.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kari.korpela@lut.fi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.core;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Delivery address info
 */
@ApiModel(description = "Delivery address info")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-05T15:39:37.700+02:00")
public class DeliveryAddress {
  @SerializedName("Postbox")
  private String postbox = null;

  @SerializedName("StreetName")
  private String streetName = null;

  @SerializedName("CityName")
  private String cityName = null;

  @SerializedName("PostalZone")
  private String postalZone = null;

  @SerializedName("CountrySubEntity")
  private String countrySubEntity = null;

  @SerializedName("Country")
  private Country country = null;

  public DeliveryAddress postbox(String postbox) {
    this.postbox = postbox;
    return this;
  }

   /**
   * Get postbox
   * @return postbox
  **/
  @ApiModelProperty(example = "PL 12", value = "")
  public String getPostbox() {
    return postbox;
  }

  public void setPostbox(String postbox) {
    this.postbox = postbox;
  }

  public DeliveryAddress streetName(String streetName) {
    this.streetName = streetName;
    return this;
  }

   /**
   * Get streetName
   * @return streetName
  **/
  @ApiModelProperty(example = "Teollisuuskatu 1", value = "")
  public String getStreetName() {
    return streetName;
  }

  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }

  public DeliveryAddress cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * Get cityName
   * @return cityName
  **/
  @ApiModelProperty(example = "Kaupunki", value = "")
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public DeliveryAddress postalZone(String postalZone) {
    this.postalZone = postalZone;
    return this;
  }

   /**
   * Get postalZone
   * @return postalZone
  **/
  @ApiModelProperty(example = "12340", value = "")
  public String getPostalZone() {
    return postalZone;
  }

  public void setPostalZone(String postalZone) {
    this.postalZone = postalZone;
  }

  public DeliveryAddress countrySubEntity(String countrySubEntity) {
    this.countrySubEntity = countrySubEntity;
    return this;
  }

   /**
   * Get countrySubEntity
   * @return countrySubEntity
  **/
  @ApiModelProperty(example = "PIRKANMAA", value = "")
  public String getCountrySubEntity() {
    return countrySubEntity;
  }

  public void setCountrySubEntity(String countrySubEntity) {
    this.countrySubEntity = countrySubEntity;
  }

  public DeliveryAddress country(Country country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public Country getCountry() {
    return country;
  }

  public void setCountry(Country country) {
    this.country = country;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryAddress deliveryAddress = (DeliveryAddress) o;
    return Objects.equals(this.postbox, deliveryAddress.postbox) &&
        Objects.equals(this.streetName, deliveryAddress.streetName) &&
        Objects.equals(this.cityName, deliveryAddress.cityName) &&
        Objects.equals(this.postalZone, deliveryAddress.postalZone) &&
        Objects.equals(this.countrySubEntity, deliveryAddress.countrySubEntity) &&
        Objects.equals(this.country, deliveryAddress.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postbox, streetName, cityName, postalZone, countrySubEntity, country);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryAddress {\n");
    
    sb.append("    postbox: ").append(toIndentedString(postbox)).append("\n");
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    postalZone: ").append(toIndentedString(postalZone)).append("\n");
    sb.append("    countrySubEntity: ").append(toIndentedString(countrySubEntity)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

