/*
 * DBE Core Complete API
 * Complete DBE Core API with all the defined API operations. Different API operations are also provided based on DBE Core roles as separate APIs.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kari.korpela@lut.fi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.core;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Delivery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-05T15:39:37.700+02:00")
public class Delivery {
  @SerializedName("RequestedDeliveryPeriod")
  private RequestedDeliveryPeriod requestedDeliveryPeriod = null;

  @SerializedName("DeliveryAddress")
  private DeliveryAddress deliveryAddress = null;

  public Delivery requestedDeliveryPeriod(RequestedDeliveryPeriod requestedDeliveryPeriod) {
    this.requestedDeliveryPeriod = requestedDeliveryPeriod;
    return this;
  }

   /**
   * Get requestedDeliveryPeriod
   * @return requestedDeliveryPeriod
  **/
  @ApiModelProperty(value = "")
  public RequestedDeliveryPeriod getRequestedDeliveryPeriod() {
    return requestedDeliveryPeriod;
  }

  public void setRequestedDeliveryPeriod(RequestedDeliveryPeriod requestedDeliveryPeriod) {
    this.requestedDeliveryPeriod = requestedDeliveryPeriod;
  }

  public Delivery deliveryAddress(DeliveryAddress deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
    return this;
  }

   /**
   * Get deliveryAddress
   * @return deliveryAddress
  **/
  @ApiModelProperty(value = "")
  public DeliveryAddress getDeliveryAddress() {
    return deliveryAddress;
  }

  public void setDeliveryAddress(DeliveryAddress deliveryAddress) {
    this.deliveryAddress = deliveryAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Delivery delivery = (Delivery) o;
    return Objects.equals(this.requestedDeliveryPeriod, delivery.requestedDeliveryPeriod) &&
        Objects.equals(this.deliveryAddress, delivery.deliveryAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestedDeliveryPeriod, deliveryAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Delivery {\n");
    
    sb.append("    requestedDeliveryPeriod: ").append(toIndentedString(requestedDeliveryPeriod)).append("\n");
    sb.append("    deliveryAddress: ").append(toIndentedString(deliveryAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

