/*
 * DBE Core Complete API
 * Complete DBE Core API with all the defined API operations. Different API operations are also provided based on DBE Core roles as separate APIs.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kari.korpela@lut.fi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.core;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Item
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-05T15:39:37.700+02:00")
public class Item {
  @SerializedName("Description")
  private String description = null;

  @SerializedName("AdditionalItemIdentification")
  private String additionalItemIdentification = null;

  @SerializedName("ItemSpecificationDocumentReference")
  private Attachement itemSpecificationDocumentReference = null;

  public Item description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Item additionalItemIdentification(String additionalItemIdentification) {
    this.additionalItemIdentification = additionalItemIdentification;
    return this;
  }

   /**
   * Get additionalItemIdentification
   * @return additionalItemIdentification
  **/
  @ApiModelProperty(value = "")
  public String getAdditionalItemIdentification() {
    return additionalItemIdentification;
  }

  public void setAdditionalItemIdentification(String additionalItemIdentification) {
    this.additionalItemIdentification = additionalItemIdentification;
  }

  public Item itemSpecificationDocumentReference(Attachement itemSpecificationDocumentReference) {
    this.itemSpecificationDocumentReference = itemSpecificationDocumentReference;
    return this;
  }

   /**
   * Get itemSpecificationDocumentReference
   * @return itemSpecificationDocumentReference
  **/
  @ApiModelProperty(value = "")
  public Attachement getItemSpecificationDocumentReference() {
    return itemSpecificationDocumentReference;
  }

  public void setItemSpecificationDocumentReference(Attachement itemSpecificationDocumentReference) {
    this.itemSpecificationDocumentReference = itemSpecificationDocumentReference;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.description, item.description) &&
        Objects.equals(this.additionalItemIdentification, item.additionalItemIdentification) &&
        Objects.equals(this.itemSpecificationDocumentReference, item.itemSpecificationDocumentReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, additionalItemIdentification, itemSpecificationDocumentReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    additionalItemIdentification: ").append(toIndentedString(additionalItemIdentification)).append("\n");
    sb.append("    itemSpecificationDocumentReference: ").append(toIndentedString(itemSpecificationDocumentReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

