/*
 * DBE Core Complete API
 * Complete DBE Core API with all the defined API operations. Different API operations are also provided based on DBE Core roles as separate APIs.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kari.korpela@lut.fi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.core;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Change order message
 */
@ApiModel(description = "Change order message")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-05T15:39:37.700+02:00")
public class OrderChange {
  @SerializedName("CustomizationID")
  private String customizationID = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("IssueDate")
  private LocalDate issueDate = null;

  @SerializedName("IssueTime")
  private OffsetDateTime issueTime = null;

  @SerializedName("NoteType")
  private String noteType = null;

  @SerializedName("BuyerCustomerParty")
  private BuyerCustomerParty buyerCustomerParty = null;

  @SerializedName("SellerSupplierParty")
  private SellerSupplierParty sellerSupplierParty = null;

  @SerializedName("Delivery")
  private Delivery delivery = null;

  @SerializedName("OrderLine")
  private List<OrderLine> orderLine = null;

  @SerializedName("SalesOrderID")
  private String salesOrderID = null;

  @SerializedName("OrderReference")
  private String orderReference = null;

  @SerializedName("SequenceNumberID")
  private String sequenceNumberID = null;

  public OrderChange customizationID(String customizationID) {
    this.customizationID = customizationID;
    return this;
  }

   /**
   * Get customizationID
   * @return customizationID
  **/
  @ApiModelProperty(value = "")
  public String getCustomizationID() {
    return customizationID;
  }

  public void setCustomizationID(String customizationID) {
    this.customizationID = customizationID;
  }

  public OrderChange ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public OrderChange issueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * Get issueDate
   * @return issueDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
  }

  public OrderChange issueTime(OffsetDateTime issueTime) {
    this.issueTime = issueTime;
    return this;
  }

   /**
   * Get issueTime
   * @return issueTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getIssueTime() {
    return issueTime;
  }

  public void setIssueTime(OffsetDateTime issueTime) {
    this.issueTime = issueTime;
  }

  public OrderChange noteType(String noteType) {
    this.noteType = noteType;
    return this;
  }

   /**
   * Get noteType
   * @return noteType
  **/
  @ApiModelProperty(value = "")
  public String getNoteType() {
    return noteType;
  }

  public void setNoteType(String noteType) {
    this.noteType = noteType;
  }

  public OrderChange buyerCustomerParty(BuyerCustomerParty buyerCustomerParty) {
    this.buyerCustomerParty = buyerCustomerParty;
    return this;
  }

   /**
   * Get buyerCustomerParty
   * @return buyerCustomerParty
  **/
  @ApiModelProperty(value = "")
  public BuyerCustomerParty getBuyerCustomerParty() {
    return buyerCustomerParty;
  }

  public void setBuyerCustomerParty(BuyerCustomerParty buyerCustomerParty) {
    this.buyerCustomerParty = buyerCustomerParty;
  }

  public OrderChange sellerSupplierParty(SellerSupplierParty sellerSupplierParty) {
    this.sellerSupplierParty = sellerSupplierParty;
    return this;
  }

   /**
   * Get sellerSupplierParty
   * @return sellerSupplierParty
  **/
  @ApiModelProperty(value = "")
  public SellerSupplierParty getSellerSupplierParty() {
    return sellerSupplierParty;
  }

  public void setSellerSupplierParty(SellerSupplierParty sellerSupplierParty) {
    this.sellerSupplierParty = sellerSupplierParty;
  }

  public OrderChange delivery(Delivery delivery) {
    this.delivery = delivery;
    return this;
  }

   /**
   * Get delivery
   * @return delivery
  **/
  @ApiModelProperty(value = "")
  public Delivery getDelivery() {
    return delivery;
  }

  public void setDelivery(Delivery delivery) {
    this.delivery = delivery;
  }

  public OrderChange orderLine(List<OrderLine> orderLine) {
    this.orderLine = orderLine;
    return this;
  }

  public OrderChange addOrderLineItem(OrderLine orderLineItem) {
    if (this.orderLine == null) {
      this.orderLine = new ArrayList<OrderLine>();
    }
    this.orderLine.add(orderLineItem);
    return this;
  }

   /**
   * Get orderLine
   * @return orderLine
  **/
  @ApiModelProperty(value = "")
  public List<OrderLine> getOrderLine() {
    return orderLine;
  }

  public void setOrderLine(List<OrderLine> orderLine) {
    this.orderLine = orderLine;
  }

  public OrderChange salesOrderID(String salesOrderID) {
    this.salesOrderID = salesOrderID;
    return this;
  }

   /**
   * Get salesOrderID
   * @return salesOrderID
  **/
  @ApiModelProperty(value = "")
  public String getSalesOrderID() {
    return salesOrderID;
  }

  public void setSalesOrderID(String salesOrderID) {
    this.salesOrderID = salesOrderID;
  }

  public OrderChange orderReference(String orderReference) {
    this.orderReference = orderReference;
    return this;
  }

   /**
   * Get orderReference
   * @return orderReference
  **/
  @ApiModelProperty(value = "")
  public String getOrderReference() {
    return orderReference;
  }

  public void setOrderReference(String orderReference) {
    this.orderReference = orderReference;
  }

  public OrderChange sequenceNumberID(String sequenceNumberID) {
    this.sequenceNumberID = sequenceNumberID;
    return this;
  }

   /**
   * Get sequenceNumberID
   * @return sequenceNumberID
  **/
  @ApiModelProperty(value = "")
  public String getSequenceNumberID() {
    return sequenceNumberID;
  }

  public void setSequenceNumberID(String sequenceNumberID) {
    this.sequenceNumberID = sequenceNumberID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderChange orderChange = (OrderChange) o;
    return Objects.equals(this.customizationID, orderChange.customizationID) &&
        Objects.equals(this.ID, orderChange.ID) &&
        Objects.equals(this.issueDate, orderChange.issueDate) &&
        Objects.equals(this.issueTime, orderChange.issueTime) &&
        Objects.equals(this.noteType, orderChange.noteType) &&
        Objects.equals(this.buyerCustomerParty, orderChange.buyerCustomerParty) &&
        Objects.equals(this.sellerSupplierParty, orderChange.sellerSupplierParty) &&
        Objects.equals(this.delivery, orderChange.delivery) &&
        Objects.equals(this.orderLine, orderChange.orderLine) &&
        Objects.equals(this.salesOrderID, orderChange.salesOrderID) &&
        Objects.equals(this.orderReference, orderChange.orderReference) &&
        Objects.equals(this.sequenceNumberID, orderChange.sequenceNumberID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customizationID, ID, issueDate, issueTime, noteType, buyerCustomerParty, sellerSupplierParty, delivery, orderLine, salesOrderID, orderReference, sequenceNumberID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderChange {\n");
    
    sb.append("    customizationID: ").append(toIndentedString(customizationID)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    issueTime: ").append(toIndentedString(issueTime)).append("\n");
    sb.append("    noteType: ").append(toIndentedString(noteType)).append("\n");
    sb.append("    buyerCustomerParty: ").append(toIndentedString(buyerCustomerParty)).append("\n");
    sb.append("    sellerSupplierParty: ").append(toIndentedString(sellerSupplierParty)).append("\n");
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    orderLine: ").append(toIndentedString(orderLine)).append("\n");
    sb.append("    salesOrderID: ").append(toIndentedString(salesOrderID)).append("\n");
    sb.append("    orderReference: ").append(toIndentedString(orderReference)).append("\n");
    sb.append("    sequenceNumberID: ").append(toIndentedString(sequenceNumberID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

