/*
 * DBE Core Complete API
 * Complete DBE Core API with all the defined API operations. Different API operations are also provided based on DBE Core roles as separate APIs.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kari.korpela@lut.fi
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.core;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Objects;


/**
 * Quotation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-02-05T15:39:37.700+02:00")
public class Quotation {
  @SerializedName("CustomizationID")
  private String customizationID = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("IssueDate")
  private LocalDate issueDate = null;

  @SerializedName("IssueTime")
  private OffsetDateTime issueTime = null;

  @SerializedName("NoteType")
  private String noteType = null;

  @SerializedName("BuyerCustomerParty")
  private BuyerCustomerParty buyerCustomerParty = null;

  @SerializedName("SellerSupplierParty")
  private SellerSupplierParty sellerSupplierParty = null;

  @SerializedName("Delivery")
  private Delivery delivery = null;

  @SerializedName("OrderLine")
  private OrderLine orderLine = null;

  @SerializedName("ValidityPeriod")
  private String validityPeriod = null;

  public Quotation customizationID(String customizationID) {
    this.customizationID = customizationID;
    return this;
  }

   /**
   * Get customizationID
   * @return customizationID
  **/
  @ApiModelProperty(value = "")
  public String getCustomizationID() {
    return customizationID;
  }

  public void setCustomizationID(String customizationID) {
    this.customizationID = customizationID;
  }

  public Quotation ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public Quotation issueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
    return this;
  }

   /**
   * Get issueDate
   * @return issueDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getIssueDate() {
    return issueDate;
  }

  public void setIssueDate(LocalDate issueDate) {
    this.issueDate = issueDate;
  }

  public Quotation issueTime(OffsetDateTime issueTime) {
    this.issueTime = issueTime;
    return this;
  }

   /**
   * Get issueTime
   * @return issueTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getIssueTime() {
    return issueTime;
  }

  public void setIssueTime(OffsetDateTime issueTime) {
    this.issueTime = issueTime;
  }

  public Quotation noteType(String noteType) {
    this.noteType = noteType;
    return this;
  }

   /**
   * Get noteType
   * @return noteType
  **/
  @ApiModelProperty(value = "")
  public String getNoteType() {
    return noteType;
  }

  public void setNoteType(String noteType) {
    this.noteType = noteType;
  }

  public Quotation buyerCustomerParty(BuyerCustomerParty buyerCustomerParty) {
    this.buyerCustomerParty = buyerCustomerParty;
    return this;
  }

   /**
   * Get buyerCustomerParty
   * @return buyerCustomerParty
  **/
  @ApiModelProperty(value = "")
  public BuyerCustomerParty getBuyerCustomerParty() {
    return buyerCustomerParty;
  }

  public void setBuyerCustomerParty(BuyerCustomerParty buyerCustomerParty) {
    this.buyerCustomerParty = buyerCustomerParty;
  }

  public Quotation sellerSupplierParty(SellerSupplierParty sellerSupplierParty) {
    this.sellerSupplierParty = sellerSupplierParty;
    return this;
  }

   /**
   * Get sellerSupplierParty
   * @return sellerSupplierParty
  **/
  @ApiModelProperty(value = "")
  public SellerSupplierParty getSellerSupplierParty() {
    return sellerSupplierParty;
  }

  public void setSellerSupplierParty(SellerSupplierParty sellerSupplierParty) {
    this.sellerSupplierParty = sellerSupplierParty;
  }

  public Quotation delivery(Delivery delivery) {
    this.delivery = delivery;
    return this;
  }

   /**
   * Get delivery
   * @return delivery
  **/
  @ApiModelProperty(value = "")
  public Delivery getDelivery() {
    return delivery;
  }

  public void setDelivery(Delivery delivery) {
    this.delivery = delivery;
  }

  public Quotation orderLine(OrderLine orderLine) {
    this.orderLine = orderLine;
    return this;
  }

  public Quotation addOrderLineItem(LineItem orderLineItem) {
    if (this.orderLine == null) {
        this.orderLine = new OrderLine();
    }
    this.orderLine.add(orderLineItem);
    return this;
  }

   /**
   * Get orderLine
   * @return orderLine
  **/
  @ApiModelProperty(value = "")
  public OrderLine getOrderLine() {
    return orderLine;
  }

  public void setOrderLine(OrderLine orderLine) {
    this.orderLine = orderLine;
  }

  public Quotation validityPeriod(String validityPeriod) {
    this.validityPeriod = validityPeriod;
    return this;
  }

   /**
   * Get validityPeriod
   * @return validityPeriod
  **/
  @ApiModelProperty(value = "")
  public String getValidityPeriod() {
    return validityPeriod;
  }

  public void setValidityPeriod(String validityPeriod) {
    this.validityPeriod = validityPeriod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Quotation quotation = (Quotation) o;
    return Objects.equals(this.customizationID, quotation.customizationID) &&
        Objects.equals(this.ID, quotation.ID) &&
        Objects.equals(this.issueDate, quotation.issueDate) &&
        Objects.equals(this.issueTime, quotation.issueTime) &&
        Objects.equals(this.noteType, quotation.noteType) &&
        Objects.equals(this.buyerCustomerParty, quotation.buyerCustomerParty) &&
        Objects.equals(this.sellerSupplierParty, quotation.sellerSupplierParty) &&
        Objects.equals(this.delivery, quotation.delivery) &&
        Objects.equals(this.orderLine, quotation.orderLine) &&
        Objects.equals(this.validityPeriod, quotation.validityPeriod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customizationID, ID, issueDate, issueTime, noteType, buyerCustomerParty, sellerSupplierParty, delivery, orderLine, validityPeriod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Quotation {\n");
    
    sb.append("    customizationID: ").append(toIndentedString(customizationID)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    issueDate: ").append(toIndentedString(issueDate)).append("\n");
    sb.append("    issueTime: ").append(toIndentedString(issueTime)).append("\n");
    sb.append("    noteType: ").append(toIndentedString(noteType)).append("\n");
    sb.append("    buyerCustomerParty: ").append(toIndentedString(buyerCustomerParty)).append("\n");
    sb.append("    sellerSupplierParty: ").append(toIndentedString(sellerSupplierParty)).append("\n");
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    orderLine: ").append(toIndentedString(orderLine)).append("\n");
    sb.append("    validityPeriod: ").append(toIndentedString(validityPeriod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

